name: built_collection
version: 3.1.0
description: >
  Immutable collections using the builder pattern.
authors:
- David Morgan <davidmorgan@google.com>
- Matan Lurey <matanl@google.com>
- Philipp Schiffmann <philippschiffmann93@gmail.com>
homepage: https://github.com/google/built_collection.dart

environment:
  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  collection: '^1.7.0'
  quiver: '>=0.21.0 <0.29.0'

dev_dependencies:
  test: any
